[project]
name = "home-budgeter"
description = "An app for proactive budgeting and transaction tracking."
authors = [
    { name = "Caroline Jeffra" , email = "caroline.jeffra@gmail.com" }
]
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "fastapi>=0.141.1",
    "psycopg[binary]>=3.3.4",
    "pydantic-settings>=2.15.0",
    "sqlalchemy[asyncio]>=2.0.52",
    "uvicorn[standard]>=0.52.3",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.3",
]

  [tool.pytest.ini_options]
  asyncio_mode = "auto"
  pythonpath = ["."]
