"""unique account name and iban

Revision ID: 2a288d01017b
Revises: 3019da5ed327
Create Date: 2026-09-01 21:44:08.578372

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a288d01017b"
down_revision: str | Sequence[str] | None = "3019da5ed327"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_accounts_iban"), "accounts", ["iban"])
    op.create_unique_constraint(op.f("uq_accounts_name"), "accounts", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_accounts_name"), "accounts", type_="unique")
    op.drop_constraint(op.f("uq_accounts_iban"), "accounts", type_="unique")
    # ### end Alembic commands ###
