"""transaction balance and account bank name

Revision ID: 33d1b7828532
Revises: 2a288d01017b
Create Date: 2026-09-06 22:09:12.416417

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '33d1b7828532'
down_revision: str | Sequence[str] | None = '2a288d01017b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('bank_name', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('balance_after_cents', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(
        op.f('uq_transactions_account_id'),
        'transactions',
        ['account_id', 'balance_after_cents', 'amount_cents']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_transactions_account_id'), 'transactions', type_='unique')
    op.drop_column('transactions', 'balance_after_cents')
    op.drop_column('accounts', 'bank_name')
    # ### end Alembic commands ###
