"""import batches

Revision ID: 34f60fbdf597
Revises: 55c1d5cec0dc
Create Date: 2026-10-06 22:28:38.982583

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34f60fbdf597"
down_revision: str | Sequence[str] | None = "55c1d5cec0dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("file_sha256", sa.String(), nullable=False),
        sa.Column("raw_bytes", sa.LargeBinary(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "bank_profile",
            sa.Enum("abn_amro", name="bank_name", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("normalizer_version", sa.Integer(), nullable=False),
        sa.Column("rows_read", sa.Integer(), nullable=False),
        sa.Column("inserted", sa.Integer(), nullable=False),
        sa.Column("skipped", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_import_batches_account_id_accounts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
        sa.UniqueConstraint("account_id", "file_sha256", name=op.f("uq_import_batches_account_id")),
    )
    op.add_column("transactions", sa.Column("raw_description", sa.String(), nullable=False))
    op.add_column("transactions", sa.Column("normalizer_version", sa.Integer(), nullable=False))
    op.add_column("transactions", sa.Column("import_batch_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_transactions_import_batch_id_import_batches"),
        "transactions",
        "import_batches",
        ["import_batch_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_transactions_import_batch_id_import_batches"), "transactions", type_="foreignkey"
    )
    op.drop_column("transactions", "import_batch_id")
    op.drop_column("transactions", "normalizer_version")
    op.drop_column("transactions", "raw_description")
    op.drop_table("import_batches")
    # ### end Alembic commands ###
